mongodb-university/realm-template-apps

android-kotlin/app/src/main/java/com/mongodb/app/Item.kt, android-kotlin/app/src/main/java/com/mongodb/app/ItemAdapter.kt, android-kotlin/app/src/main/java/com/mongodb/app/ItemsActivity.kt, android-kotlin/app/src/main/java/com/mongodb/app/LoginActivity.kt, android-kotlin/app/src/main/res/layout/item_view.xml, android-kotlin/app/src/main/res/values/ids.xml, android-kotlin/app/src/main/res/values/strings.xml
WIP, currently the three dots just functions as a delete button rather than generating a popup menu
=> DOCSP-14518 Android - Implement item deletion

generated/web-graphql/src/components/RealmApp.js, generated/web-graphql/src/hooks/useTodos_graphql.js, generated/web-graphql/src/hooks/useTodos_mql.js, generated/web-mql/src/components/RealmApp.js, generated/web-mql/src/hooks/useTodos_graphql.js, generated/web-mql/src/hooks/useTodos_mql.js, web-js/src/components/RealmApp.js, web-js/src/hooks/useTodos_graphql.js, web-js/src/hooks/useTodos_mql.js
Fixes small integration issues we uncovered in the QA session
- Lowercase collection name
- Remove extra console.log
- Use dynamic baseUrl for GraphQL
=> [Web - GraphQL/MQL] QA

react-native/package-lock.json, react-native/package.json
- (supposedly)
- Pins to 10.0.0 which pulls latest minor version
=> Upgrade realm dependency in RN to fix baseUrl issue

electron/package.json, electron/src/renderer/App.jsx, electron/src/renderer/components/Todo.jsx, electron/src/renderer/components/WelcomePage.js, electron/src/renderer/index.ejs
change includes: 
* ui tweaks to change app name
* error messages on log in / sign up page 
* update package.json to refer to this application, not the starter boilerplate
=> UI Tweaks & change package.json info

flex-sync-permissions/backend/tiered-backend/realm_config.json, flex-sync-permissions/client/src/addCollaboratorsExample.js, flex-sync-permissions/client/src/getRealm.js, flex-sync-permissions/client/src/index.js, flex-sync-permissions/client/src/logInOrRegister.js, flex-sync-permissions/client/src/realm.json, flex-sync-permissions/client/src/restrictedFeedExample.js, flex-sync-permissions/client/src/tieredExample.js, flex-sync-permissions/generated/add-collaborators/src/addCollaboratorsExample.js, flex-sync-permissions/generated/add-collaborators/src/getRealm.js, flex-sync-permissions/generated/add-collaborators/src/index.js, flex-sync-permissions/generated/add-collaborators/src/logInOrRegister.js, flex-sync-permissions/generated/add-collaborators/src/realm.json, flex-sync-permissions/generated/restricted-feed/src/getRealm.js, flex-sync-permissions/generated/restricted-feed/src/index.js, flex-sync-permissions/generated/restricted-feed/src/logInOrRegister.js, flex-sync-permissions/generated/restricted-feed/src/realm.json, flex-sync-permissions/generated/restricted-feed/src/restrictedFeedExample.js, flex-sync-permissions/generated/tiered/src/getRealm.js, flex-sync-permissions/generated/tiered/src/index.js, flex-sync-permissions/generated/tiered/src/logInOrRegister.js, flex-sync-permissions/generated/tiered/src/tieredExample.js
- Move logIn and getRealm to reusable
- Remove CLI options, instead read from realm.json
=> Refactor flex sync

generated/swiftui-flexible-sync/App/Views/OpenRealmView.swift, swiftui/App/Views/OpenRealmView.swift
This PR:
- Removes unused `SubscriptionState` code
=> SwiftUI Flexible Sync Template App Fixes

flutter/pubspec.yaml
update flutter sdk version b/c of bug with the Realm SDK `0.3.0+beta` release that doesn't download the Realm binaries correctly. 
see https://github.com/realm/realm-dart/blob/master/CHANGELOG.md#031beta-2022-06-07
=> fix flutter sdk version

flutter/ios/Podfile.lock, flutter/lib/components/create_todo.dart, flutter/lib/realm/schemas.dart, flutter/lib/realm/schemas.g.dart, flutter/lib/screens/log_in.dart, flutter/lib/viewmodels/todo_viewmodel.dart, flutter/pubspec.lock
done to make more inline with standard practices and other template apps
relates to https://github.com/mongodb-university/realm-template-apps/pull/79
=> Update Flutter app to use ObjectId as PK

flutter/lib/components/item_card.dart, flutter/lib/viewmodels/item_viewmodel.dart
some code that should be in only in the tutorial final state is in the base template. removing that code. no impact on the template app functionality.
=> Flutter Template App: Remove stuff that shouldn't be in base template

flutter/README.md, flutter/android/build.gradle, flutter/lib/components/create_item.dart, flutter/macos/Podfile.lock, flutter/macos/Runner/DebugProfile.entitlements, flutter/macos/Runner/Release.entitlements
- remove print statement
- update README with more info about building app for emulator
- fix Android and macOS build issues
=> (DOCSP-25003): flutter template app tweaks

flutter_todo/README.md, kotlin-sdk/README.md, react-native/README.md, swiftui/README.md, xamarin/README.md
Reverts mongodb-university/realm-template-apps#114
...in order to re-trigger the action workflow
=> Revert "Update READMEs with setup details when cloning from GitHub"

tools/validate-manifest/src/validate.test.ts, tools/validate-manifest/src/validate.ts
This could have prevented a flub in the refactor
=> Add backend config litmus test to validator

v2/swiftui/App/Views/ItemRow.swift, v2/swiftui/App/Views/LoginView.swift
For staged swiftui app
* Update button color
* Add visual indicator if user own's an item
Visual:
https://user-images.githubusercontent.com/25092858/207698876-f19b21db-04a6-43d6-94b4-c343be4857f7.png
https://user-images.githubusercontent.com/25092858/207698877-e84f4e46-50e6-4383-bc4d-874d214f1bea.png
=> Use green and mine

sync-todo/v2/client/swiftui/App.xcodeproj/project.pbxproj
- Use version realm 10.32.3 in the swiftui template app
=> Use version 10.32.3

sync-todo/v2/client/flutter/pubspec.lock, sync-todo/v2/client/flutter/pubspec.yaml, sync-todo/v2/generated/flutter/pubspec.lock, sync-todo/v2/generated/flutter/pubspec.yaml
Pending the next Flutter SDK release: update the Flutter template app versions in `pubspec.yaml`.
https://github.com/mongodb-university/realm-template-apps/blob/e359b675791d11c3f55d29e4e25bcba3964e857a/sync-todo/v2/client/flutter/pubspec.yaml
=> (DOCSP-30014) Update Flutter SDK template app versions

sync-todo/v2/backend/sync/config.json
https://jira.mongodb.org/browse/DOCSP-31383
=> add max offline time to template app

sync-todo/v2/client/react-native/atlasConfig.json, sync-todo/v2/client/react-native/package-lock.json, sync-todo/v2/client/react-native/src/App.tsx, sync-todo/v2/client/react-native/src/ItemListView.tsx
As part of [DOCSP-30612](https://jira.mongodb.org/browse/DOCSP-30612), add links to the Data Explorer view so that it's easy for users to see their data in Atlas.
=> Add Data Explorer message to React Native template

sync-todo/v2/client/swiftui/App.xcodeproj/project.pbxproj, sync-todo/v2/client/swiftui/App/App.swift, sync-todo/v2/generated/swiftui/App.xcodeproj/project.pbxproj, sync-todo/v2/generated/swiftui/App/App.swift
This PR removes two deprecated config options from the App config, and bumps the Swift SDK package version.
=> SwiftUI: remove deprecated config options

sync-todo/v2/client/react-native/package-lock.json, sync-todo/v2/generated/react-native/package-lock.json
In my previous PR (#166), I made some Git mistakes. I took some changes Caleb had made and invalidated my `package-lock.json` changes.
This PR fixes that mistake.
=> Regenerate `packag-lock.json` again

other/web-js/client/package-lock.json, other/web-js/generated/prod-data-api/package-lock.json, other/web-js/generated/prod-graphql/package-lock.json, other/web-js/generated/prod-mql/package-lock.json
I've upgraded dependencies in the web-js template app to fix security vulnerabilities. I've tested all three of the generated apps locally and everything works as expected.
=> web-js templates: Upgrade dependencies to fix security vulnerabilities

sync-todo/v2/client/flutter/README.md, sync-todo/v2/client/flutter/pubspec.lock, sync-todo/v2/client/flutter/pubspec.yaml, sync-todo/v2/generated/flutter/README.md, sync-todo/v2/generated/flutter/pubspec.lock, sync-todo/v2/generated/flutter/pubspec.yaml
The linked Jira ticket: https://jira.mongodb.org/browse/DOCSP-34632
Calls for me to investigate the issue reported in the forum: [Flexible Sync Flutter App does not appear to sync properly](https://www.mongodb.com/community/forums/t/flexible-sync-sample-flutter-app-does-not-appear-to-sync-properly/255202)
I was not able to replicate this Sync issue. I'm able to create new documents from both the device and in Atlas, change values, and see the updated values reflected on the device. I can't speak to whether this might have been an issue with an older version of the SDK, as I updated dependencies before I attempted to replicate this error.
I did encounter the issue reported in #168 . I'm checking with engineering to see if it is safe for us to populate a default value for this field, or if …
=> (DOCSP-34632): Flutter: Update dependencies and the README

.github/workflows/push-artifact-cpp.yml
Jira ticket: https://jira.mongodb.org/browse/DOCSP-36596
=> (DOCSP-36596): Add a workflow to push the C++ template app to the artifact repo

sync-todo/v2/client/flutter/README.md, sync-todo/v2/client/flutter/assets/config/atlasConfig.json, sync-todo/v2/client/flutter/lib/components/app_bar.dart, sync-todo/v2/client/flutter/lib/components/create_item.dart, sync-todo/v2/client/flutter/lib/components/modify_item.dart, sync-todo/v2/client/flutter/lib/components/todo_item.dart, sync-todo/v2/client/flutter/lib/components/todo_list.dart, sync-todo/v2/client/flutter/lib/main.dart, sync-todo/v2/client/flutter/lib/realm/schemas.dart, sync-todo/v2/client/flutter/lib/realm/schemas.realm.dart, sync-todo/v2/client/flutter/lib/screens/homepage.dart, sync-todo/v2/client/flutter/lib/screens/log_in.dart, sync-todo/v2/client/flutter/lib/theme.dart, sync-todo/v2/client/flutter/pubspec.lock, sync-todo/v2/client/flutter/pubspec.yaml, sync-todo/v2/generated/flutter/README.md, sync-todo/v2/generated/flutter/lib/components/app_bar.dart, sync-todo/v2/generated/flutter/lib/components/create_item.dart, sync-todo/v2/generated/flutter/lib/components/modify_item.dart, sync-todo/v2/generated/flutter/lib/components/todo_item.dart, sync-todo/v2/generated/flutter/lib/components/todo_list.dart, sync-todo/v2/generated/flutter/lib/main.dart, sync-todo/v2/generated/flutter/lib/realm/schemas.dart, sync-todo/v2/generated/flutter/lib/realm/schemas.realm.dart, sync-todo/v2/generated/flutter/lib/screens/homepage.dart, sync-todo/v2/generated/flutter/lib/screens/log_in.dart, sync-todo/v2/generated/flutter/lib/theme.dart, sync-todo/v2/generated/flutter/pubspec.lock, sync-todo/v2/generated/flutter/pubspec.yaml
Jira: https://jira.mongodb.org/browse/DOCSP-37311
- Upgrade Flutter template app to v2.0.0
- Use `.realm.dart` part files
- Improve README 
- Update deprecated properties
Note: Will generate with updates after they're reviewed
=> DOCSP-37311: Upgrade to Flutter v2 and improve README

other/edge-server/client/README.md
I missed a step in the quick start. This PR fixes that.
=> Add missing step

sync-todo/v2/client/swiftui/App.xcodeproj/project.pbxproj, sync-todo/v2/client/swiftui/App/atlasConfig.plist, sync-todo/v2/generated/swiftui/App.xcodeproj/project.pbxproj
This [fixes a problem with initial subscriptions](https://github.com/realm/realm-swift/releases/tag/v10.50.1) introduced in v10.50.0.
=> Update SwiftUI client to SDK v10.50.1
