mongodb-university/realm-template-apps

xamarin/realm-todo-dotnet/App.xaml.cs
xamarin/realm-todo-dotnet/LoginPage.xaml
xamarin/realm-todo-dotnet/LoginPage.xaml.cs
xamarin/realm-todo-dotnet/TaskPage.xaml.cs

- Fixed: When starting the app while already logged in, and then logging out, the app would not close the existing task view. Upon re-log in, crash due to realm already being opened. Also, pushing the login view is incorrect here as a second logout would then pop to root, which would have been the first task view.
- Unified font size between sign up/sign in views for less distraction.
- Fixed: When logging out and returning to the login view, the isLoggingIn could be set to the incorrect state.

Xamarin quick fixes

---

xamarin/realm-todo-dotnet/LoginPage.xaml.cs

- Removed current user check since this method is only ever called in the context where
current user is definitely null
- Move unsafe code into try block

Fix null reference exception on any login alert

---

.github/workflows/zip-everything-and-upload-to-s3.yml
manifest.json

- Use a new zip file name so that we can merge things and update the zip file. When backend team is ready to consume it, they can change the name of the zip file they are looking for.
- Add flex sync versions to manifest file

Update manifest and zip file name

---

react-native/.eslintrc.js
react-native/package-lock.json
react-native/package.json
react-native/src/App.js
react-native/src/TaskSchema.js
react-native/src/TasksView.js

JIRA: 
- https://jira.mongodb.org/browse/DOCSP-23394
Additional Fixes (not included within JIRA ticket):
- Added prettier script to package.json
- Removed rule "no-unused-vars" (since some variables are commented out for the template, but when they are generated via bluehawk, such as if they are used for the flexified template state, then they are used)
- Removed uneeded variables in TasksView.js (these variables are neither used by the flexible template state or the pbs template state)

(DOCSP-23394): Remove deleteRealmIfMigrationNeeded + Lint/Prettier improvements

---

flutter_todo/README.md
flutter_todo/assets/config/realm.json
flutter_todo/lib/realm/schemas.g.dart
flutter_todo/macos/Podfile.lock
flutter_todo/pubspec.lock
flutter_todo/pubspec.yaml

Update Realm Flutter SDK to 0.6.0+beta. fixes a bug wher schema migrations don't work when doing non-breaking client side changes. 
also updated README to reference the tutorial and app id to one that is currently active.

(DOCSP-26228): Update Realm Flutter SDK to 0.6.0+beta

---

sync-todo/v1/client/flutter_todo/README.md
sync-todo/v1/client/kotlin-sdk/README.md
sync-todo/v1/client/react-native/README.md
sync-todo/v1/client/swiftui/README.md
sync-todo/v1/client/xamarin/README.md
sync-todo/v1/generated/flutter_todo/README.md
sync-todo/v1/generated/kotlin-sdk/README.md
sync-todo/v1/generated/react-native/README.md
sync-todo/v1/generated/swiftui/README.md
sync-todo/v1/generated/xamarin/README.md
sync-todo/v2/client/flutter/README.md
sync-todo/v2/client/kotlin-sdk/README.md
sync-todo/v2/client/maui/README.md
sync-todo/v2/client/react-native/README.md
sync-todo/v2/client/swiftui/README.md

When you download the template app client as a Zip file, the app is not populated with an App ID. Adding instructions to the READMEs about how to find and populate the App IDs in this scenario.
Also, adding some things to the v2 READMEs that were missing.
Maui was missing a README entirely. I've added config details here, but we should probably add any notable instructions to run the app and/or change the namespace similar to the Xamarin README.

Add Zip download App ID instructions to READMEs

---

sync-todo/v2/generated/swiftui/App.xcodeproj/project.pbxproj

Forgot to generate the new version of the SwiftUI App after bumping the SDK version in the base app.

Update generated SwiftUI App SDK version

---

sync-todo/v2/client/react-native/package.json

After the latest Xcode release, builds for iOS started having errors.  This has been fixed in a patch version of React Native.

Update React Native to work with latest Xcode

---

sync-todo/v2/client/swiftui/App/Views/ItemList.swift
sync-todo/v2/generated/swiftui/App/Views/ItemList.swift

This matches the behavior of other template apps, and ensures a consistent ordering in the view

add a sort to swift template app

---

sync-todo/v2/client/kotlin-sdk/app/src/main/java/com/mongodb/app/ComposeItemActivity.kt
sync-todo/v2/client/kotlin-sdk/app/src/main/java/com/mongodb/app/TemplateApp.kt
sync-todo/v2/client/kotlin-sdk/app/src/main/java/com/mongodb/app/ui/tasks/AddItem.kt
sync-todo/v2/generated/kotlin-sdk/app/src/main/java/com/mongodb/app/ComposeItemActivity.kt
sync-todo/v2/generated/kotlin-sdk/app/src/main/java/com/mongodb/app/TemplateApp.kt
sync-todo/v2/generated/kotlin-sdk/app/src/main/java/com/mongodb/app/ui/tasks/AddItem.kt

In Kotlin template app only, the string resource in `atlasConfig.xml` is generated as `realm_data_explorer_link`, which doesn't match the in-code ref.

Fix dataExplorerLink ref in Kotlin template app

---

other/flex-sync-guides/backend/tiered/functions/config.json

JIRA: https://jira.mongodb.org/browse/BAAS-22432
While working on updating our TSA parsing code, I ran into a validation error because one of the apps had a function defined in the functions config that didn't have a corresponding source file, so I removed the declaration

BAAS-22432: remove undeclared function in tiered sync app function config

---

other/triggers/triggers/trigger0.json

JIRA: https://jira.mongodb.org/browse/BAAS-26004
See https://github.com/10gen/baas/pull/11842 for the wider context, but the tl;dr is that having the `function_name` as a top-level field on the trigger config was causing some trouble with our new code for parsing backend templates. Once that PR is merged, the top-level `function_name` would work, but I'm opting to put this up just to have the trigger reflect our current structure

BAAS-26004: Update trigger template to use event_processors syntax for function name

---

sync-todo/v2/generated/kotlin-sdk/app/src/main/res/values/atlasConfig.xml
sync-todo/v2/template-atlasConfig.xml

My fix in #182 didn't fix the missing data explorer link in Kotlin. I didn't realize that the bluehawk script was replacing the contents of the client's `atlasConfig.xml` with a sanitized version, so the change I made in the client file was being overwritten by the sanitized one without that field.
This PR updates the sanitized version and the generated app's `atlasConfig.xml`.

Fix missing data explorer link in Kotlin

---

other/edge-server/backend/auth/providers.json
other/edge-server/client/README.md

Update README with steps outlining how to create an App Services App that uses the project's pre-configured backend. 
(These steps can only be tested once the `edge-server-template` branch is merged to `main` and the new `edge-server.todo` template is available via CLI.)

DOCSP-35656: Update README for App Services backend

---

README.md
other/edge-server/client/README.md

Add a few documentation links and README tweaks based on testing the Edge Server template.
When we merge this PR, it should trigger a new push to the artifact repo, remove the `backend` directory, and display this README as the root of the artifact repo.

Edge Server: Add and update details in README

---

sync-todo/v2/client/kotlin-sdk/app/build.gradle.kts
sync-todo/v2/client/kotlin-sdk/build.gradle.kts
sync-todo/v2/client/kotlin-sdk/gradle/wrapper/gradle-wrapper.properties
sync-todo/v2/generated/kotlin-sdk/app/build.gradle.kts
sync-todo/v2/generated/kotlin-sdk/build.gradle.kts
sync-todo/v2/generated/kotlin-sdk/gradle/wrapper/gradle-wrapper.properties

Update Kotlin template app from v1.8.0 to v1.13.0 and update any dependencies

DOCSP-36923: Bump Kotlin app to v1.13.0

---

sync-todo/v2/client/swiftui/App.xcodeproj/project.pbxproj
sync-todo/v2/generated/swiftui/App.xcodeproj/project.pbxproj

Per this Jira ticket: https://jira.mongodb.org/browse/DOCSP-39201
These updates change the way we use Realm with Swift Package Manager in the SwiftUI template app to build successfully with the Privacy Manifest, per the changes in [v10.49.3](https://github.com/realm/realm-swift/releases/tag/v10.49.3). And the Core updates in [v10.50.0](https://github.com/realm/realm-swift/releases/tag/v10.50.0) resolve the remaining outstanding issue with using the `@AutoOpen` property wrapper reported in #183 .

SwiftUI: Update to 10.50.0, change SPM build settings

---

sync-todo/v2/client/swiftui/App.xcodeproj/project.pbxproj
sync-todo/v2/generated/swiftui/App.xcodeproj/project.pbxproj

After merging and testing #204, I found that 10.50.0 introduces a breaking change to initial subscriptions that causes the template app to crash.
While waiting for info from engineering, I'm downgrading the template app to only use v10.49.3 instead of using next major to avoid users encountering this issue.

Use exact Swift version 10.49.3 to avoid breaking changes

---

sync-todo/v2/client/cpp/CMakeLists.txt
sync-todo/v2/client/cpp/README.md
sync-todo/v2/client/cpp/atlasConfig.json
sync-todo/v2/client/cpp/controllers/app_controller.cpp
sync-todo/v2/client/cpp/controllers/home_controller.cpp
sync-todo/v2/client/cpp/controllers/home_controller.hpp
sync-todo/v2/client/cpp/managers/auth_manager.cpp
sync-todo/v2/client/cpp/managers/auth_manager.hpp
sync-todo/v2/client/cpp/managers/database_manager.cpp
sync-todo/v2/client/cpp/managers/database_manager.hpp
sync-todo/v2/generated/cpp/CMakeLists.txt
sync-todo/v2/generated/cpp/README.md
sync-todo/v2/generated/cpp/controllers/app_controller.cpp
sync-todo/v2/generated/cpp/controllers/home_controller.cpp
sync-todo/v2/generated/cpp/controllers/home_controller.hpp
sync-todo/v2/generated/cpp/managers/auth_manager.cpp
sync-todo/v2/generated/cpp/managers/auth_manager.hpp
sync-todo/v2/generated/cpp/managers/database_manager.cpp
sync-todo/v2/generated/cpp/managers/database_manager.hpp

- Handle auth errors
- Adjust button and window constraints so the button labels are less likely to disappear
- Use a delegate to have the `HomeController` change its own state, instead of letting `DatabaseManager` mutate its state, per this PR review comment: https://github.com/mongodb-university/realm-template-apps/pull/197#discussion_r1543176629
Note for reviewer: after making this change, IntelliSense is saying the DatabaseManager constructor is never used, and is warning me that the `_delegate` I added to the DatabaseManager may be null. I'm not getting those warnings in the other places that have delegates (AuthManager/AppController, for example). So I think I may have missed something here - BUT it is all working properly.

C++ Template App Follow-Ups

---

sync-todo/v2/client/react-native/ios/Podfile

* In this version of React Native, current versions of Xcode are not compatible with Flipper dependencies
* This commit disable Flipper from being installed in the Pod Install phase
* In effect, this will avoid failures when using the template

Remove Flipper

---

.github/workflows/verify-bluehawk.yml

Adds a github action to verify all files in /client are also in /generated. This ensures that the PR submitter has run bluehawk.

Add GH action to verify all files in /client are also in /generated
